FROM centos:8 as phase_1


RUN yum -y install  gcc-c++ rrdtool perl-Time-HiRes perl-rrdtool php-gd php php-cli wget mlocate \
    git postfix \
    zsh telnet openssh-server rpm-build nodejs \
    haproxy jq chrony rng-tools automake cmake gcc tcpdump bind-utils nmap-ncat at tar  \
    npm
