FROM centos:7 as phase_1

#RUN head -c 5 /dev/random > random_bytes && find /var/cache/rpms -type f | wc -l && \
#    find /var/cache/dnf -type f | wc -l  && \
#    find /var/cache/yum -type f | wc -l 

COPY files/*.rpm /usr/src

RUN sed -i 's/^installonly_limit=3/installonly_limit=60/g' /etc/yum.conf
RUN yum install -y epel-release dnf && \
    sed -i 's/^installonly_limit=3/installonly_limit=60/g' /etc/dnf/dnf.conf && \
    dnf -4 -y install \
                    /usr/src/ok-release.rpm /usr/src/labs-consol-stable.rhel7.noarch.rpm \
                    /usr/src/ncpa-2.2.2.el7.x86_64.rpm /usr/src/daemontools-encore-1.11-1.el7.x86_64.rpm && \
    rm -f /usr/src/*.rpm

# INSTALL PACKAGES
RUN dnf -4 -y install --exclude=nagiosxx --enablerepo=ok-testing \
	gcc-c++ rrdtool perl-Time-HiRes perl-rrdtool php-gd php php-cli wget mlocate \
    naemon naemon-livestatus adagios okconfig pnp4nagios which \
	git postfix python-pip python3-pip python3-devel python-devel acl python-setuptools \
	zsh telnet openssh-server ansible-python3 openvpn openvpn-devel rpm-build tinyproxy nodejs \
    haproxy jq chrony rng-tools automake cmake gcc tcpdump ngrep bind-utils nmap-ncat at tar npm \
    fail2ban certbot tree naemon-devel redis tmux ngrep make automake net-tools \
    nagios-plugins-tcp nagios-plugins-http nagios-plugins-users nagios-plugins-smtp nagios-plugins-procs nagios-plugins-mysql \
    nagios-plugins-mailq nagios-plugins-load nagios-plugins-dns nagios-plugins-dig nagios-plugins-disk nagios-plugins-ssh \
    nagios-plugins-ping nagios-plugins-http nagios-plugins-fping nagios-plugins-by_ssh nagios-plugins-check_cpu nagios-plugins-file_age \
    nagios-plugins-icmp nagios-plugins-nagios nagios-plugins-time nagios-plugins-swap \
    strace sqlite-devel jansson-devel mariadb-devel which go vim lsof psmisc aide sysstat chkconfig bubblewrap dstat socat \
    nagios-okplugin-check_firewall_active nagios-okplugin-check_package_updates nagios-okplugin-check_ifoperstate \
    nagios-okplugin-get_network_stat nagios-okplugin-check_disks perl-Net-DNS nagios-okplugin-check_http_multi \
    python2-speedtest-cli perl-Monitoring-Plugin perl-Switch man-db python-virtualenv libacl-devel keepalived


from phase_1 as phase_cache

#RUN dnf -y makecache && yum -y makecache
#RUN dnf -y reinstall --downloadonly --destdir /var/cache/rpms '*'





from phase_cache as phase_summary

#RUN dnf list > /root/.dnf && wc -l /root/.dnf && rpm -qa|wc -l

#RUN head -c 5 /dev/random > random_bytes && find /var/cache/rpms -type f | wc -l && \
#    find /var/cache/dnf -type f | wc -l  && \
#    find /var/cache/yum -type f | wc -l 
